name: James Mathis Kane
favicon: null
layout_spectrum: 0.32407
typography_spectrum: 0.75328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98c1bd'
    - '#2e2c32'
    - '#bf9c55'
    - '#c3618a'
    - '#b42639'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
