name: James Mathis Kane
favicon: null
layout_spectrum: 0.35668754507787526
typography_spectrum: 0.6030682551208884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7757504067849368
  lightness: 0.29398850933648646
  saturation: 0.03664609440602362
  rhythmicContrast: 0.5380411949008703
purpose: []
